### ISSUE TITLE
android icons size issue [BUG] 

### ISSUE THREAD

**Issue by Ali-Fadaei** [mrrhak/icons_launcher#10]
### :information_source: Info
Version: `1.2.1`

### :speech_balloon: Description

android output launcher icon size is not fitted
can you help me to fix this issue?

### :scroll: Pubspec.yaml
flutter_icons:
  windows: true
  macos: false
  linux: false
  android: true
  ios: false
  web: true
  image_path_windows: "assets\\images\\logo\\oldMinimalLogo.png"
  image_path_macos: "assets\\images\\logo\\oldMinimalLogo.png"
  image_path_linux: "assets\\images\\logo\\oldMinimalLogo.png"
  image_path_android: "assets\\images\\logo\\oldMinimalLogo.png"
  image_path_ios: "assets\\images\\logo\\oldMinimalLogo.png"
  image_path_web: "assets\\images\\logo\\oldMinimalLogo.png"
  adaptive_icon_background: "#028A99"
  adaptive_icon_foreground: "assets\\images\\logo\\oldMinimalLogo.png"
  remove_alpha_ios: false
  remove_alpha_macos: false

<img width="84" alt="oldMinimalLogo" src="https://user-images.githubusercontent.com/46972583/176175776-43316e6d-bfcb-4216-8039-ce5fe4592652.png">

![screeshot](https://user-images.githubusercontent.com/46972583/176176114-5b0b486b-4406-40bd-b463-379646427565.jpeg)

**Comment by mrrhak** [comment]
Your icon example:

![example](https://user-images.githubusercontent.com/42771980/176203852-deca1cac-e8f2-4609-b5dd-e3a45735c73d.png)

**Comment by Ali-Fadaei** [comment]
@mrrhak thanks you 🙏🏻
