### ISSUE TITLE
[FEATURE REQUEST] how to launch icons to ipad and launch image?

### ISSUE THREAD

**Issue by anz-ryu** [mrrhak/icons_launcher#11]
<img width="1100" alt="スクリーンショット 2022-07-02 0 43 12" src="https://user-images.githubusercontent.com/96708931/176927138-4b0e6d05-9b87-4261-ad6d-b0de3dc48efa.png">

i ran the command but the icons of ipad and lauch image was not added, what sould I do?

**Comment by mrrhak** [comment]
Hi @anz-ryu
Sorry for late reply and did you run command generate icons successfully? Please provide me you command logs and pubspec config. As I test it working fine you can look at [example](https://github.com/mrrhak/icons_launcher/tree/master/example/simple_app).

![Screen Shot 2022-07-08 at 8 54 33 AM](https://user-images.githubusercontent.com/42771980/177901335-65d205cf-2e92-4623-8755-6e474199946a.png)
