### ISSUE TITLE
playstore icon location incorrect

### ISSUE THREAD

**Issue by OutdatedGuy** [mrrhak/icons_launcher#19]
### :information_source: Info

Version: `e.g. v2.0.1`

### :speech_balloon: Description

After the `2.0.0` update, the generated playstore icon is being located in `res` folder instead of the `main` folder like in `Android Studio` or previous versions.

Is this intended or just a miss located?

**Comment by mrrhak** [comment]
Yes, thank you I will fix it in the next version.
