### ISSUE TITLE
[BUG] Icons don't update on macOS desktop

### ISSUE THREAD

**Issue by danfleck** [mrrhak/icons_launcher#2]
### :information_source: Info

Version: `  icons_launcher: ^1.1.3`

### :speech_balloon: Description
When run from the CLI it seems to generate the icons, but when the app starts the icon in the desktop tray is still the default Flutter icon. Note: This actually happens also when I manually change the icons using Xcode. If the app (Runner) is started in Xcode the icons show up. If it is started from the CLI: flutter run -d macos   the default flutter icon shows up. 

Thus, I'm not sure it's a plugin problem, but maybe there is a workaround?

### :scroll: icons_launcher.yaml
flutter_icons:
  android: false
  ios: false
  macos: true
  image_path: "assets/icon/icon.png"
  remove_alpha_macos: true

**Comment by mrrhak** [comment]
Make sure icons are generated or not by opening your macos folder via Xcode and navigate to Runner->Resources->Assers.xcassets.
If icons are generated successfully please try clean your project and rebuild it again. If still can not fix please let me know. Thanks

**Comment by danfleck** [comment]
The icons were there, but didn't show up until the "flutter clean". Seems like it requires a clean after building the icons. All good now...thanks!

**Comment by Devenom1** [comment]
@mrrhak It would be awesome if you could mention that running `flutter clean` fixes this issue for MacOS/iOS in the documentation. I really like this library. I spent hours thinking it was broken on Mac OS.

Sometimes we don't realise that such simple commands can fix these issues.
