### ISSUE TITLE
[BUG]  Generating assets for iOS doesn't create the associated Contents.json in the appiconset

### ISSUE THREAD

**Issue by qixotic** [mrrhak/icons_launcher#20]
### :information_source: Info
Version: `2.0.2`

### :speech_balloon: Description
Generating assets for iOS doesn't create the associated `Contents.json` in the appiconset, nor does XCode [Version 13.4.1 (13F100)] generate one for you. 

To reproduce:
open `icons_launcher/example/simple_app/ios` in xcode, delete the existing AppIcon set, and regenerate using:
`flutter pub run icons_launcher:create --path icons_launcher.yaml`
Notice that `ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json` remains deleted, while the AppIcon view in xcode simply shows all icons as "Unassigned".

### :scroll: Pubspec.yaml
Used the example yaml in `icons_launcher/example/simple_app/pubspec.yaml`

**Comment by mrrhak** [comment]
Yes, Thank you for report. I'm will fix it soon.
