### ISSUE TITLE
[BUG] Problem when try to add package

### ISSUE THREAD

**Issue by rupas385** [mrrhak/icons_launcher#24]
### :information_source: Info

Version:  2.0.6

Flutter version: 3.3.9

### :speech_balloon: Description

When add the package I get this error:
Because icons_launcher >=1.1.0 depends on universal_io ^2.0.4 which depends on crypto ^3.0.0, icons_launcher >=1.1.0 requires crypto ^3.0.0.
So, because crypto depends on icons_launcher ^2.0.6 and crypto is 1.0.0+1, version solving failed.
pub get failed (1; So, because crypto depends on icons_launcher ^2.0.6 and crypto is 1.0.0+1, version solving failed.)

**Comment by mrrhak** [comment]
It conflicts with the nested dependency version with your other dependency and you can resolve it by upgrading the dependency that conflicts to the latest version if available or using `dependency_overrides`.

**Comment by rupas385** [comment]
I used dependency overrides and clean my proyect. Then I dont have any other dependency. Now compile, but when I call

`flutter pub run icons_launcher:create
`

Get this error,

`Failed to build icons_launcher:create:
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/adler32.dart:2:8: Error: Error when reading 'lib/crypto.dart': No such file or directory
import 'package:crypto/crypto.dart' as crypto;
       ^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/crc32.dart:2:8: Error: Error when reading 'lib/crypto.dart': No such file or directory
import 'package:crypto/crypto.dart' as crypto;
       ^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/xz_decoder.dart:3:8: Error: Error when reading 'lib/crypto.dart': No such file or directory
import 'package:crypto/crypto.dart';
       ^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/adler32.dart:32:23: Error: Type 'crypto.Hash' not found.
class Adler32 extends crypto.Hash {
                      ^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/adler32.dart:46:50: Error: Type 'crypto.Digest' not found.
  ByteConversionSink startChunkedConversion(Sink<crypto.Digest> sink) =>
                                                 ^^^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/adler32.dart:65:14: Error: Type 'crypto.Digest' not found.
  final Sink<crypto.Digest> _inner;
             ^^^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/crc32.dart:33:21: Error: Type 'crypto.Hash' not found.
class Crc32 extends crypto.Hash {
                    ^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/crc32.dart:47:50: Error: Type 'crypto.Digest' not found.
  ByteConversionSink startChunkedConversion(Sink<crypto.Digest> sink) =>
                                                 ^^^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/crc32.dart:66:14: Error: Type 'crypto.Digest' not found.
  final Sink<crypto.Digest> _inner;
             ^^^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/adler32.dart:46:57: Error: 'Digest' isn't a type.
  ByteConversionSink startChunkedConversion(Sink<crypto.Digest> sink) =>
                                                        ^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/adler32.dart:65:21: Error: 'Digest' isn't a type.
  final Sink<crypto.Digest> _inner;
                    ^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/adler32.dart:85:23: Error: Method not found: 'Digest'.
    _inner.add(crypto.Digest([
                      ^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/crc32.dart:47:57: Error: 'Digest' isn't a type.
  ByteConversionSink startChunkedConversion(Sink<crypto.Digest> sink) =>
                                                        ^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/crc32.dart:66:21: Error: 'Digest' isn't a type.
  final Sink<crypto.Digest> _inner;
                    ^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/crc32.dart:86:23: Error: Method not found: 'Digest'.
    _inner.add(crypto.Digest([
                      ^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/xz_decoder.dart:206:15: Error: The getter 'sha256' isn't defined for the class '_XZStreamDecoder'.
 - '_XZStreamDecoder' is from 'package:archive/src/xz_decoder.dart' ('../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/xz_decoder.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'sha256'.
              sha256.convert(data.toBytes().sublist(startDataLength)).bytes;
              ^^^^^^
pub finished with exit code 1
rupas@Mac-mini-de-Rube avatarme % flutter pub run icons_launcher:create
Failed to build icons_launcher:create:
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/adler32.dart:2:8: Error: Error when reading 'lib/crypto.dart': No such file or directory
import 'package:crypto/crypto.dart' as crypto;
       ^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/crc32.dart:2:8: Error: Error when reading 'lib/crypto.dart': No such file or directory
import 'package:crypto/crypto.dart' as crypto;
       ^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/xz_decoder.dart:3:8: Error: Error when reading 'lib/crypto.dart': No such file or directory
import 'package:crypto/crypto.dart';
       ^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/adler32.dart:32:23: Error: Type 'crypto.Hash' not found.
class Adler32 extends crypto.Hash {
                      ^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/adler32.dart:46:50: Error: Type 'crypto.Digest' not found.
  ByteConversionSink startChunkedConversion(Sink<crypto.Digest> sink) =>
                                                 ^^^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/adler32.dart:65:14: Error: Type 'crypto.Digest' not found.
  final Sink<crypto.Digest> _inner;
             ^^^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/crc32.dart:33:21: Error: Type 'crypto.Hash' not found.
class Crc32 extends crypto.Hash {
                    ^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/crc32.dart:47:50: Error: Type 'crypto.Digest' not found.
  ByteConversionSink startChunkedConversion(Sink<crypto.Digest> sink) =>
                                                 ^^^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/crc32.dart:66:14: Error: Type 'crypto.Digest' not found.
  final Sink<crypto.Digest> _inner;
             ^^^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/adler32.dart:46:57: Error: 'Digest' isn't a type.
  ByteConversionSink startChunkedConversion(Sink<crypto.Digest> sink) =>
                                                        ^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/adler32.dart:65:21: Error: 'Digest' isn't a type.
  final Sink<crypto.Digest> _inner;
                    ^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/adler32.dart:85:23: Error: Method not found: 'Digest'.
    _inner.add(crypto.Digest([
                      ^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/crc32.dart:47:57: Error: 'Digest' isn't a type.
  ByteConversionSink startChunkedConversion(Sink<crypto.Digest> sink) =>
                                                        ^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/crc32.dart:66:21: Error: 'Digest' isn't a type.
  final Sink<crypto.Digest> _inner;
                    ^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/util/crc32.dart:86:23: Error: Method not found: 'Digest'.
    _inner.add(crypto.Digest([
                      ^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/xz_decoder.dart:206:15: Error: The getter 'sha256' isn't defined for the class '_XZStreamDecoder'.
 - '_XZStreamDecoder' is from 'package:archive/src/xz_decoder.dart' ('../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.3.5/lib/src/xz_decoder.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'sha256'.
              sha256.convert(data.toBytes().sublist(startDataLength)).bytes;
              ^^^^^^
pub finished with exit code 1
`

**Comment by mrrhak** [comment]
I think the problem is with your `.pub_cache` folder I have tested it on my machine it works fine with the latest dependency version no need to use `dependency_overrides`.
```yaml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  icons_launcher: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  lints: ^2.0.1
```

Please try to clean your project cache with the command `flutter clean` and delete your `.pub_cache` folder and delete `pubspec.lock` file and run `flutter pub get` again. Thanks
