### ISSUE TITLE
[BUG] Not working

### ISSUE THREAD

**Issue by VinniciusJesus** [mrrhak/icons_launcher#27]
Flutter: 3.3.10
Version: `icons_launcher:  `

The error is generated when trying to run the command `flutter pub run icons_launcher:create`

Error: `Could not find bin/create.dart in package icons_launcher.`

**Comment by Pedrogvas** [comment]
firts run:
1.- `flutter pub add icons_launcher`
2.- `flutter pub get `
3.- `flutter pub run icons_launcher:create`
