### ISSUE TITLE
linux icon laucher not working

### ISSUE THREAD

**Issue by ganeshchenniah** [mrrhak/icons_launcher#30]
pubspec.yaml
  icons_launcher: 2.1.0

icons_launcher.yaml
icons_launcher:
  image_path: 'assets/images/logo.png'
  platforms:
    linux:
      enable: true
      image_path: 'assets/images/logo.png'
    android:
      enable: true

flutter pub run icons_launcher:create --path icons_launcher.yaml

╔════════════════════════════════════════════════════╗
║             ✨✨  ICONS LAUNCHER  ✨✨             ║
╠════════════════════════════════════════════════════╣
║                   Version: 2.1.0                   ║
╚════════════════════════════════════════════════════╝

🌱  Creating Android icons...
      ✅  Generated launcher icon images
      ✅  Updated android manifest launcher icon
🌱  Creating Linux icons...
      ✅  Generated app icon image

==> GENERATE LAUNCHER ICONS SUCCESSFULLY <==
            ❤️   THANK YOU! ❤️

If i start debug/release app , icon is not visible.

**Comment by mrrhak** [comment]
Currenlty, for linux I just pre-config a snap gui follow this: https://docs.flutter.dev/deployment/linux#desktop-file-and-icon
