### ISSUE TITLE
Add compatibility with Very Good CLI

### ISSUE THREAD

**Issue by alejandrogiubel** [mrrhak/icons_launcher#31]
Add compatibility with Very Good CLI flavors

**Comment by mrrhak** [comment]
You just create configuration file name follow the flavor name that Very Good CLI generated for example (`development`, `staging` and `production`).
- `icons_launcher-development.yaml`
- `icons_launcher-staging.yaml`
- `icons_launcher-production.yaml`

Then just run `dart run icons_launcher:create --flavors development,staging,production`

Read more for flavor [here](https://github.com/mrrhak/icons_launcher?tab=readme-ov-file#flavor-support)
