### ISSUE TITLE
[BUG] Aliasing in web splash images

### ISSUE THREAD

**Issue by esDotDev** [mrrhak/icons_launcher#41]
The 1x images produced for the web are showing noticeable aliasing:
![image](https://github.com/mrrhak/icons_launcher/assets/736973/ed44cbbc-a6dc-45e3-93e7-3e5bd1ed33f6)

**Comment by mrrhak** [comment]
Hi, @esDotDev 
Sorry I'm not get your point. Could you provide more detail?

**Comment by esDotDev** [comment]
Whatever algorithm is being used to re-size the images for the splash screen is introducing aliasing.
![image](https://github.com/mrrhak/icons_launcher/assets/736973/f7993b23-efb2-4320-b270-e79ec553ecdc)

We would expect it to look like this:
![image](https://github.com/mrrhak/icons_launcher/assets/736973/c9f2e799-d7f9-4796-aeae-e57d822f15f3)

**Comment by esDotDev** [comment]
Woops, sorry, I realized this is an issue with the native_splash package, not yours.
