### ISSUE TITLE
[FEATURE REQUEST] add support for notifications icons

### ISSUE THREAD

**Issue by JobMoll** [mrrhak/icons_launcher#48]
### :speech_balloon: Description
It would be awesome if this package also generates the icons for notifications.

### :question: Platform
This would be for Android.

**Comment by deandreamatias** [comment]
Duplicated #29

**Comment by mrrhak** [comment]
I have add android notification icon on this release [v3.0.0-beta.1](https://pub.dev/packages/icons_launcher/versions/3.0.0-beta.1)
