### ISSUE TITLE
[FEATURE REQUEST] Support IOS 18 Dark and Tinted Icons

### ISSUE THREAD

**Issue by Codel1417** [mrrhak/icons_launcher#49]
### :speech_balloon: Description
IOS 18 introduced themed icons. This consists of a dark icon, and a tinted icon. These new icon types use layers similar to android adaptive icons, but only a transparent foreground image is provided. The background is provided by the system.

https://developer.apple.com/documentation/Xcode/configuring-your-app-icon
https://developer.apple.com/design/human-interface-guidelines/app-icons#iOS-iPadOS

While this request is specific to IOS devices, VisionOS uses a similar system, but can have more than one layer. The code is likely the same other than setting a single metadata value. 

### :question: Platform
IOS

I am going to look into this myself to see what Apple changed to add support for tinted and dark icons

**Comment by kimhak-jtrb** [comment]
Yes, thank you. I will looking for it very soon

**Comment by mrrhak** [comment]
Currently, I am using the stable release of xCode not yet support this option so when Apple officially releases iOS 18 and xCode I will check it. Thank you.

**Comment by mrrhak** [comment]
Hi @Codel1417, Feature has been added on [`v3.0.0`](https://pub.dev/packages/icons_launcher).
