### ISSUE TITLE
[FEATURE REQUEST] multiple windows icons

### ISSUE THREAD

**Issue by matthias-steinkamp** [mrrhak/icons_launcher#8]
### :speech_balloon: Description
To get the best resolution on multiple windows explorer views (large icons, list, ...), is it possible to generate a windows .ico with multiple resolutions of the input icon file?
Also the highest resolution of 256px would be nice.

See https://stackoverflow.com/questions/3236115/which-icon-sizes-should-my-windows-applications-icon-include

### :question: Platform
Windows

**Comment by mrrhak** [comment]
Hi, @matthias-steinkamp as I see flutter windows do not support multiple resolutions icons. Currently, we generate one ico file with 128px and a default ico file only 48px.

**Comment by matthias-steinkamp** [comment]
Hi @mrrhak, thanks for the quick answer. I'm not a windows dev guru, but I think the rc-file specifies the .ico file and .ico files can hold several icon images for different sizes. Afterwards, windows automatically displays the right image for the desired view in file explorer etc. So I guess, it's not a flutter topic but just how many images are stored in the single .ico file.

"ICO files contain one or more small images at multiple sizes and color depths, such that they may be scaled appropriately." https://en.wikipedia.org/wiki/ICO_(file_format)

**Comment by mrrhak** [comment]
Ohh thanks for clearly explaining. After I'm checking on this [image](https://pub.dev/packages/image) package I think I can try to create a single .ico file from multiple sizes as you want.

**Comment by mrrhak** [comment]
Hi @matthias-steinkamp I have change windows .ico quality from 128px to 256px in new version [v1.2.0](https://pub.dev/packages/icons_launcher). You can check a generated .ico file [here](https://redketchup.io/icon-editor) to see multiple sizes have been embedded. Thanks

**Comment by matthias-steinkamp** [comment]
the generated icon shows one 256px only

**Comment by mrrhak** [comment]
I have fixed in v1.2.1

**Comment by matthias-steinkamp** [comment]
Yes, it works fine! Thanks for the very fast response and help!
